version: 2
jobs:
  test:
    docker:
      - image: circleci/elixir:1.8.1
    steps:
      - checkout
      - run:
          name: Get dependencies
          command: mix deps.get
      - run:
          name: Compile
          command: mix compile
      - run:
          name: Run tests
          command: mix test
      - run:
          name: "Verify results.xml"
          command: |
            mkdir -p /tmp/test-results
            find _build -name results.xml -exec mv {} /tmp/test-results \;
      - run:
          name: Verify results.xml has contents
          command: test -s /tmp/test-results/results.xml
      - store_artifacts:
          path: /tmp/test-results/results.xml
          destination: test-results
      - store_test_results:
          path: /tmp/test-results/results.xml

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
